app:
  name: "EiTec VPN Server"
  port: 8080
  mode: "release"  # debug, release, test
  secret: "eitec-vpn-server-secret-key-2024"
  listen: ":8070"
  read_timeout: 15s
  write_timeout: 15s
  idle_timeout: 60s
  max_header_bytes: 1
  server_ip: "192.168.50.1"  # 服务器的公网或内网IP地址，用于生成WireGuard配置
  tls:
    enabled: false
    listen: ":8443"
    cert_file: ""
    key_file: ""

wireguard:
  interface: "wg0"
  port: 51820
  network: "10.10.0.0/24"
  dns: "8.8.8.8,8.8.4.4"
  sync_interval: 300

database:
  type: "sqlite"
  path: "data/eitec-vpn.db"

auth:
  admin_username: "admin"
  admin_password: "admin123"
  jwt_secret: "your-jwt-secret-key-change-this-in-production"
  refresh_secret: "your-refresh-secret-key-change-this-in-production"
  access_expiry: 1h
  refresh_expiry: 24h
  session_timeout: 24h

logging:
  level: "info"  # debug, info, warn, error
  file: "logs/server.log"
  max_size: 100  # MB
  max_backups: 7
  max_age: 30  # days 